#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
update_cwl.py — 从 structure.sty 自动提取定理环境，更新 TeXStudio 补全文件 yukina-beamer.cwl

用法：
    python update_cwl.py [输出路径]

默认输出（两份）：
    1. 项目内  .\\cwl\\yukina-beamer.cwl           （入库，随模板分发）
    2. 用户级  %APPDATA%\\texstudio\\completion\\user\\yukina-beamer.cwl
               （TeXStudio 实际加载位置）

逻辑：
    1. 解析 structure.sty 模块 II：
       - \\yukina@defthm{ENV}{中文名}{主色}{计数器}  -> 编号环境，带 {标题}{label} 两个参数
       - \\newenvironment{ENV}                       -> 无参环境（proof/answer/solution）
       - \\newenvironment{hint}[1][提示]              -> 可选参数环境（hint）
       - \\lstnewenvironment{code}[1][]               -> 代码环境（code，可选参数）
    2. 生成 `\\begin{ENV}... #T` 形式的环境补全条目（#T 为 TeXStudio 环境标记）。

注意：数学符号库（模块 IV 的 \\newcommand）由 TeXStudio 自动生成
（autogenerated/structure.cwl），本脚本不重复处理。

改动 structure.sty 的环境定义后运行本脚本即可同步；TeXStudio 重启后生效。
"""
import os
import re
import shutil
import sys
import pathlib

SCRIPT_DIR = pathlib.Path(__file__).resolve().parent

STRUCTURE = SCRIPT_DIR / "structure.sty"
PROJECT_CWL = SCRIPT_DIR / "cwl" / "yukina-beamer.cwl"

# TeXStudio 补全文件位置：按 %APPDATA% 推导，避免写死本机用户名
_APPDATA = os.environ.get("APPDATA") or (pathlib.Path.home() / "AppData" / "Roaming")
DEFAULT_CWL = pathlib.Path(_APPDATA) / "texstudio" / "completion" / "user" / "yukina-beamer.cwl"

# 编号环境: \yukina@defthm{env}{中文名}{主色}{计数器}
THM_RE = re.compile(r"\\yukina@defthm\{([A-Za-z@]+)\}")
# 普通环境: \newenvironment{env}  /  \lstnewenvironment{env}
ENV_RE = re.compile(r"\\(?:lst)?newenvironment\{([A-Za-z@]+)\}")


def extract_environments(structure_path):
    """从 structure.sty 提取环境清单，返回 (env, kind) 列表。

    kind: 'thm'  编号环境（{标题}{label}）
          'plain' 无参环境
          'opt'  可选参数环境 [提示]
    """
    text = pathlib.Path(structure_path).read_text(encoding="utf-8")
    idx = text.find("[模块 II]")
    if idx != -1:
        text = text[idx:]

    envs = []
    for line in text.splitlines():
        s = line.strip()
        m = THM_RE.search(s)
        if m:
            envs.append((m.group(1), "thm"))
            continue
        m = ENV_RE.match(s)
        if m:
            name = m.group(1)
            # hint / code 带可选参数 [默认值]
            kind = "opt" if "[1][" in s or "[1][]" in s else "plain"
            envs.append((name, kind))
    return envs


def generate_cwl(envs):
    """生成 cwl 内容。"""
    lines = [
        "# TeXStudio completion entries for Beamer template by Yukina.",
        "# 由 update_cwl.py 从 structure.sty 自动生成, 请勿手改。",
        "# 环境名与「笔记写作」模板一致: \\begin{env}{标题}{label} ... \\end{env}",
        "",
    ]
    for name, kind in envs:
        if kind == "thm":
            lines.append(f"\\begin{{{name}}}{{title}}{{label}}#T")
        elif kind == "opt":
            lines.append(f"\\begin{{{name}}}[#t]#T")
        else:
            lines.append(f"\\begin{{{name}}}#T")
        lines.append(f"\\end{{{name}}}#T")
        lines.append("")
    return "\n".join(lines)


def main():
    if not STRUCTURE.exists():
        print(f"错误: 找不到 structure.sty ({STRUCTURE})")
        return 1

    envs = extract_environments(STRUCTURE)
    if not envs:
        print("错误: 未从 structure.sty 提取到任何环境")
        return 1

    content = generate_cwl(envs)
    PROJECT_CWL.parent.mkdir(parents=True, exist_ok=True)
    PROJECT_CWL.write_text(content, encoding="utf-8")
    print(f"[1/2] 已生成项目补全文件: {PROJECT_CWL}")

    # 用户级输出（TeXStudio 加载位置），可指定
    out = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_CWL
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(content, encoding="utf-8")
    print(f"[2/2] 已写入 TeXStudio 补全目录: {out}")

    names = ", ".join(n for n, _ in envs)
    print(f"共 {len(envs)} 个环境: {names}")
    print("TeXStudio 重启后生效（若未自动加载, 请到 选项→补全 勾选 yukina-beamer.cwl）。")
    return 0


if __name__ == "__main__":
    sys.exit(main())
